### ISSUE TITLE
warning require.extensions is not supported by webpack. Use a loader instead. 

### ISSUE THREAD

**Issue by cyrildurand** [mohsen1/yawn-yaml#104]
I have the following warning with `my create-react-app` and `typescript` when I use yawn-yaml

```
Compiled with warnings.

./node_modules/yaml-js/lib/yaml.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.

./node_modules/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.

./node_modules/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.
``` 

I have this error when I import yawn using 

    import Yawn from "yawn-yaml/cjs";

**Comment by cyrildurand** [comment]
I forked this project and updated all dependencies, the warning has disappear. 

You can use my fork by updating your `package.config` like this : 

    "yawn-yaml": "github:cyrildurand/yawn-yaml"

This is a temporary solution while waiting for the official package to be updated.

**Comment by cheitya** [comment]
@mohsen1 , @cyrildurand -
Are we planning to merge this update to official package?

**Comment by cyrildurand** [comment]
I made a pull request https://github.com/mohsen1/yawn-yaml/pull/105 but don't have any response

**Comment by 501351981** [comment]
https://github.com/501351981/form2yaml  This JS library solves all known bugs

**Comment by mohsen1** [comment]
v2 should solve this
