### ISSUE TITLE
Breaks when changing multiple values (due to non-deterministic behaviour)

### ISSUE THREAD

**Issue by vdh** [mohsen1/yawn-yaml#13]
Inside whatever non-deterministic magic is happening with setting a new object on `yawn.json`, if the whole object is replaced with more than one change, that cascades into causing miscellaneous parser errors to be thrown from `yaml-js`.

I only managed to find out why this was happening while trying to comment and uncomment huge swaths of my Yaml data files. I noticed when there was just one value changed, no errors were thrown, but if multiple values changed at the same time, `yaml-js` cried bloody murder with all sorts of `ParserError.YAMLError` errors, such as `expected <block end>, but found <scalar>` and `special characters are not allowed`…

😢

**Comment by mohsen1** [comment]
Can you paste steps to reproduce or better a pr with failing tests?

**Comment by vdh** [comment]
@mohsen1 Created a PR with a failing test: #14
