### ISSUE TITLE
babelfied and wrapped version for nodejs

### ISSUE THREAD

**Issue by Celadora** [mohsen1/yawn-yaml#15]
Hi, we wrapped a babelfied version of the library and forked the repo. We'd like to share that through a pull request. This wrapped version can be loaded using "require" instead of import.

https://github.com/Celadora/yawn-yaml

Note the new directory titled: nodejs

**Comment by mohsen1** [comment]
We do compile this to commonjs using browserify:

https://github.com/mohsen1/yawn-yaml/blob/master/package.json#L23

Why that didn't work for you?
