### ISSUE TITLE
Window dependency

### ISSUE THREAD

**Issue by d3lm** [mohsen1/yawn-yaml#17]
When I use this package in a node environment I am getting an error that says `window undefined`, which makes sense. Does this library only work in the browser?

[This](https://github.com/mohsen1/yawn-yaml/blob/master/dist/yawn.js#L97-L101) is the dist code and it accesses the dependencies through the window variable.

**Comment by mohsen1** [comment]
You probably want to use `require('yawn-yaml/cjs')` because of [this](https://github.com/mohsen1/yawn-yaml/blob/cc270a5237f9d0e9e1c58e594fafbdae89e17016/package.json#L24)
