### ISSUE TITLE
Cannot load window properties

### ISSUE THREAD

**Issue by nirgur** [mohsen1/yawn-yaml#4]
Hi
i'm trying to use your library with react and getting errors because window.yaml & window.jsyaml are not defined
tried to import it without success
when modify your code to load it as "require('js-yaml')" it worked
am i doing something wrong?

Thanks

**Comment by mohsen1** [comment]
This mofule had some dependencies. You need to add them as well. See bower.json

**Comment by mohsen1** [comment]
Like this: https://github.com/mohsen1/yawn-yaml/blob/master/demo/index.html#L4

**Comment by nirgur** [comment]
added it by using import 'js-yaml' but there is no such property window.yaml
is there a specific way i need to load it?

**Comment by mohsen1** [comment]
just add the scripts to the HTML page.

**Comment by nirgur** [comment]
the page is generated automatically, i cannot add it
can you please load it by using required instead of loading it from the window?
in this way it will be also possible to run it in node server

**Comment by nirgur** [comment]
in this way:

var _yamlJs = require('yaml-js');

var _jsYaml = require('js-yaml');

var _lodash = require('lodash');

**Comment by mohsen1** [comment]
If you're using ES6, depend on actual source:
https://github.com/mohsen1/yawn-yaml/blob/master/src/index.js

If you're using ES5 but want to use commonjs module system, this module does not have it. You can make a pull request and I'll merge it. To do that, add a gulp task that generates ES5 version of source without concatenating all of dependencies and store it in `dist` folder and name it `yawn.commonjs.js`
