### ISSUE TITLE
TypeError: _lodash is undefined

### ISSUE THREAD

**Issue by dudif91** [mohsen1/yawn-yaml#82]
Hi,
when trying to run let yawn = new YAWN(yaml);
i'm getting this error TypeError: _lodash is undefined

**Comment by cyrildurand** [comment]
How did you import YAWN ? I had the same issue and fix it by importing like this : 

import Yawn from "yawn-yaml/cjs";

**Comment by cheitya** [comment]
import Yawn from "yawn-yaml/cjs"; - This resolved the _loadash is undefined error

But it gives a console error saying-
ERROR in ./node_modules/yaml-js/lib/yaml.js
Module not found: Error: Can't resolve 'fs' in '/node_modules/yaml-js/lib'

**Comment by foolstar3** [comment]
I have come to a problem like this `Cannot read properties of undefined (reading 'isString')`, and it's came out in the construcor function.

**Comment by foolstar3** [comment]
> 

Thanks, bro. I did as you said, and it works.

**Comment by foolstar3** [comment]
> How did you import YAWN ? I had the same issue and fix it by importing like this :
> 
> import Yawn from "yawn-yaml/cjs";
Thanks, bro. I did as you said, and it works.

**Comment by foolstar3** [comment]
> How did you import YAWN ? I had the same issue and fix it by importing like this :
> 
> import Yawn from "yawn-yaml/cjs";

Thanks, bro. I did as you said, and it works.

**Comment by mohsen1** [comment]
v2 should not have this problem
