### ISSUE TITLE
Cross-platform line break support

### ISSUE THREAD

**Issue by kevinswiber** [mohsen1/yawn-yaml#9]
For this particular case, `require('os').EOL` should be used instead of the constant `LINE_SEPERATOR`, which has a value of `\n`.

https://github.com/mohsen1/yawn-yaml/blob/d870fbe1767ae429fa012414404aaae2a49f44fb/src/index.js#L317-L320

**Comment by mohsen1** [comment]
Good idea! PR is welcome!

**Comment by kevinswiber** [comment]
As I'm building on top of this project, I'm cataloguing some of the issues.  When I get a breather, I'll be happy to submit PRs!

**Comment by kevinswiber** [comment]
Hey, @mohsen1, it looks like the contents of `dist` and `cjs` weren't built before this was published.  Still having issues, unfortunately.  :grimacing:

**Comment by mohsen1** [comment]
Oops sorry! Fixing it right now!

**Comment by mohsen1** [comment]
Done in `yawn-yaml@1.3.2`
